- hosts: db
  become: yes

  tasks:
      - name: Get docker compose file from repository
        get_url:
            url: https://gitlab.com/bbwrl/m346-ref-card-03/-/raw/main/docker-compose.yml
            dest: .

      # Docker installation
      - name: Update & Upgrade
        ansible.builtin.apt:
            name: aptitude
            state: present
            update_cache: true

      - name: Install dependencies
        ansible.builtin.apt:
            name:
                - net-tools
                - apt-transport-https
                - ca-certificates
                - curl
                - software-properties-common
                - python3-pip
                - virtualenv
                - python3-setuptools
                - gnupg-agent
                - autoconf
                - dpkg-dev
                - file
                - g++
                - gcc
                - libc-dev
                - make
                - pkg-config
                - re2c
                - wget
            state: present
            update_cache: true

      - name: Add Docker GPG apt Key
        ansible.builtin.apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

      - name: Add repository into sources list
        ansible.builtin.apt_repository:
            repo: deb https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
            state: present
            filename: docker

      - name: Install Docker
        ansible.builtin.apt:
            name:
                - docker-ce
                - docker-ce-cli
                - docker-compose
                - containerd.io
            state: present
            update_cache: true

      - name: Setup docker user
        ansible.builtin.user:
            name: jannis
            groups: "docker"
            append: true

      - name: Install Docker module for Python
        ansible.builtin.pip:
            name: docker

      - name: Restart Docker
        ansible.builtin.service:
            name: docker
            state: restarted
            enabled: true

      - name: Create docker containers
        community.docker.docker_compose:
            project_src: .
        register: output
