- hosts: web
  become: yes

  tasks:
      - name: Clone of a single branch
        git:
            repo: https://gitlab.com/bbwrl/m346-ref-card-03.git
            dest: ./m346-ref-card-03
            single_branch: yes
            version: main

      - name: Install packages
        apt:
            pkg:
                - openjdk-11-jdk
                - maven
            state: latest
            update_cache: true

      - name: Build maven package
        shell: "cd ./m346-ref-card-03 && mvn package"

      - name: Run java application
        shell: "cd ./m346-ref-card-03 && java -DDB_USERNAME='jokedbuser' -DDB_PASSWORD='123456' -DDB_URL='jdbc:mariadb://{{ hostvars['db1'].ansible_host }}/jokedb' -jar target/architecture-refcard-03-0.0.1-SNAPSHOT.jar"

      - name: Get docker compose file from repository
        get_url:
            url: https://raw.githubusercontent.com/LorenzHohermuth/m346-ref-cards-3-ansible/main/spring.service
            dest: /etc/systemd/system

      - name: Start systemd service
        shell: |
            systemctl daemon-reload
            systemctl start spring.service
            systemctl enable spring.service
