- hosts: web
  become: yes

  tasks:
      - name: Clone of a single branch
        git:
            repo: https://gitlab.com/bbwrl/m346-ref-card-03.git
            dest: .
            single_branch: yes
            version: main

      - name: Change to repository directory
        shell: "cd m346-ref-card-03"

      - name: Install packages
        apt:
            pkg:
                - openjdk-11-jdk
                - maven
            state: latest
            update_cache: true

      - name: Build maven package
        shell: "mvn package"

      - name: Run java application
        shell: "java -DDB_USERNAME='jokedbuser' -DDB_PASSWORD='123456' -jar target/architecture-refcard-03-0.0.1-SNAPSHOT.jar"
